[workspace]
members = ["ataraxia-proto", "ataraxia-lexer", "ataraxia-parser", "ataraxia-interpreter", "ataraxia"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ataraxia-proto = { path = "ataraxia-proto" }
ataraxia-lexer = { path = "ataraxia-lexer" }
ataraxia-parser = { path = "ataraxia-parser" }
ataraxia-interpreter = { path = "ataraxia-interpreter" }
chumsky = { version = "1.0.0-alpha.7", features = ["nightly", "label"] }
dyn-clone = "1.0.17"
gc = { version = "0.5.0", features = ["derive", "nightly"] }
logos = "0.14.0"
ordered-float = "4.2.2"
rug = { version = "1.25.0", default-features = false, features = ["integer"] }